### ISSUE TITLE
This does not set the zone it just sets zone to the zonefile

### ISSUE THREAD

**Issue by anoncam** [grramos/action-named-checkzone#1]
https://github.com/grramos/action-named-checkzone/blob/0a29629256ca5da9f4646b64a8ec5b2dda8e8af5/docker-entrypoint.sh#L12

**Comment by bwbroersma** [comment]
Thanks for fixing.
I was wondering why I was seeing :heavy_check_mark: for this faulty [zone file example](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/4/html/reference_guide/s2-bind-zone-examples):
![image](https://github.com/grramos/action-named-checkzone/assets/4252918/5126e377-4360-40eb-8d62-9567fb3a8fc4)

Using a pin on your PR #2 like this:
```yml
    - name: Run named-checkzone
      uses: grramos/action-named-checkzone@30482b39d522c076d41c0ccdfe9737d9c3c6678a
```
will result in the desired :x::
![image](https://github.com/grramos/action-named-checkzone/assets/4252918/fd86907f-5b56-4158-b13a-afa9e8403215)

**Comment by anoncam** [comment]
#2
